[build]
command = "rm -rf .next node_modules/.cache && pnpm run build"
publish = ".next"

[build.environment]
NODE_OPTIONS = "--max-old-space-size=4096"

[template.environment]
OPENAI_API_KEY = "set your OpenAI API Key"
